services:
  - type: web
    name: toyswebsite
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: VITE_RAZORPAY_KEY_ID
        sync: false
      - key: VITE_RAZORPAY_SECRET_KEY
        sync: false
